version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migration
    command: ["-url=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}",
              "-user=${POSTGRES_USER}",
              "-password=${POSTGRES_PASSWORD}",
              "-locations=filesystem:/flyway/sql",
              "-connectRetries=5",
              "migrate"]
    depends_on  :
      - postgres
    volumes:
      - ./flyway/sql:/flyway/sql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_application
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
